//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cuenta_Por_Pagar
{
    using System;
    using System.Collections.Generic;
    
    public partial class FACTURASvictorP
    {
        public int NUMEROFACTURA { get; set; }
        public string CODIGO { get; set; }
        public Nullable<decimal> VALORFACTURA { get; set; }
        public Nullable<System.DateTime> FECHAFACTURA { get; set; }
        public Nullable<System.DateTime> FECHAVENCIMIENTO { get; set; }
    }
}
