//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cuenta_Por_Pagar
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SCXPvictorPEntities : DbContext
    {
        public SCXPvictorPEntities()
            : base("name=SCXPvictorPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CHEQUESvictorP> CHEQUESvictorP { get; set; }
        public virtual DbSet<FACTURASvictorP> FACTURASvictorP { get; set; }
        public virtual DbSet<PROVEEDORESvictorP> PROVEEDORESvictorP { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Table> Table { get; set; }
        public virtual DbSet<USUARIOSvictorP> USUARIOSvictorP { get; set; }
        public virtual DbSet<ESTADODECUENTAS> ESTADODECUENTAS { get; set; }
    }
}
